name: Pulumi
on:
  pull_request:
    branches:
     - 'master'
  push:
    branches:
      - 'master'
env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_GITHUB_TOKEN }}
  PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
  GITHUB_OWNER: stackpath

jobs:
  preview:
    name: Run Pulumi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true

      - run: npm install

      - name: run pulumi preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: trsdev
          cloud-url: gs://trspulumitest
          comment-on-pr: true
          github-token: ${{ secrets.PULUMI_GITHUB_TOKEN }}
          diff: true

      - name: run pulumi up
        uses: pulumi/actions@v3
        # only run this step if we are pushing to master
        if: ${{ github.ref == 'refs/heads/master'}}
        with:
          command: up
          stack-name: trsdev
          cloud-url: gs://trspulumitest
          diff: true
          github-token: ${{ secrets.PULUMI_GITHUB_TOKEN }}
