name: Pulumi
on:
  push:
    branches:
      - master

# permissions: write-all

jobs:
  up:
    name: up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - id: run-pulumi
        uses: ./.github/actions/pulumi
        with:
          github-token: ${{ secrets.PULUMI_GITHUB_TOKEN }}
          gcs-sa-key: ${{ secrets.GC_SA_KEY }}
          gc-project: ${{ secrets.GC_PROJECT }}
          pulumi-backend-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          pulumi-command: up
          stack-name: trsdev
          gcs-url: gs://trspulumitest
              

